// healthService exists for performance testing on timur.mobi.
// It is not included for regular use.

package main

/*
	L'attelage du sommeil, semblable à celui du soleil, va d'un pas si égal, dans une atmosphère où ne peut plus l'arrêter aucune résistance, qu'il faut quelque petit caillou aérolithique étranger à nous (dardé de l'azur par quel Inconnu) pour atteindre le sommeil régulier (qui sans cela n'aurait aucune raison de s'arrêter et durerait d'un mouvement pareil jusque dans les siècles des siècles) et le faire, d'une brusque courbe, revenir vers le réel, brûler les étapes, traverser les régions voisines de la vie—où bientôt le dormeur entendra, de celle-ci, les rumeurs presque vagues encore, mais déjà perceptibles, bien que déformées—et atterrir brusquement au réveil. Alors de ces sommeils profonds on s'éveille dans une aurore, ne sachant qui on est, n'étant personne, neuf, prêt à tout, le cerveau se trouvant vidé de ce passé qui était la vie jusque-là. Et peut-être est-ce plus beau encore quand l'atterrissage du réveil se fait brutalement et que nos pensées du sommeil, dérobées par une chape d'oubli, n'ont pas le temps de revenir progressivement avant que le sommeil ne cesse. Alors du noir orage qu'il nous semble avoir traversé (mais nous ne disons même pas nous) nous sortons gisants, sans pensées, un «nous» qui serait sans contenu. Quel coup de marteau l'être ou la chose qui est là a-t-elle reçu pour tout ignorer, stupéfaite jusqu'au moment où la mémoire accourue lui rend la conscience ou la personnalité? Encore, pour ces deux genres de réveil, faut-il ne pas s'endormir, même profondément, sous la loi de l'habitude. Car tout ce que l'habitude enserre dans ses filets, elle le surveille, il faut lui échapper, prendre le sommeil au moment où on croyait faire tout autre chose que dormir, prendre en un mot un sommeil qui ne demeure pas sous la tutelle de la prévoyance, avec la compagnie, même cachée, de la réflexion.

	Du moins, dans ces réveils tels que je viens de les décrire, et qui étaient la plupart du temps les miens quand j'avais dîné la veille à la Raspelière, tout se passait comme s'il en était ainsi, et je peux en témoigner, moi l'étrange humain qui, en attendant que la mort le délivre, vis les volets clos, ne sais rien du monde, reste immobile comme un hibou et, comme celui-ci, ne vois un peu clair que dans les ténèbres. Tout se passe comme s'il en était ainsi, mais peut-être seule une couche d'étoupe a-t-elle empêché le dormeur de percevoir le dialogue intérieur des souvenirs et le verbiage incessant du sommeil. Car (ce qui peut, du reste, s'expliquer aussi bien dans le premier système, plus vaste, plus mystérieux, plus astral) au moment où le réveil se produit, le dormeur entend une voix intérieure qui lui dit: «Viendrez-vous à ce dîner ce soir, cher ami? comme ce serait agréable!» et pense: «Oui, comme ce sera agréable, j'irai»; puis, le réveil s'accentuant, il se rappelle soudain: «Ma grand'mère n'a plus que quelques semaines à vivre, assure le docteur.» Il sonne, il pleure à l'idée que ce ne sera pas, comme autrefois, sa grand'mère, sa grand'mère mourante, mais un indifférent valet de chambre qui va venir, lui répondre. Du reste, quand le sommeil l'emmenait si loin hors du monde habité par le souvenir et la pensée, à travers un éther où il était seul, plus que seul, n'ayant même pas ce compagnon où l'on s'aperçoit soi-même, il était hors du temps et de ses mesures. Déjà le valet de chambre entre, et il n'ose lui demander l'heure, car il ignore s'il a dormi, combien d'heures il a dormi (il se demande si ce n'est pas combien de jours, tant il revient le corps rompu et l'esprit reposé, le coeur nostalgique, comme d'un voyage trop lointain pour n'avoir pas duré longtemps).

	Certes on peut prétendre qu'il n'y a qu'un temps, pour la futile raison que c'est en regardant la pendule qu'on a constaté n'être qu'un quart d'heure ce qu'on avait cru une journée. Mais au moment où on le constate, on est justement un homme éveillé, plongé dans le temps des hommes éveillés, on a déserté l'autre temps. Peut-être même plus qu'un autre temps: une autre vie. Les plaisirs qu'on a dans le sommeil, on ne les fait pas figurer dans le compte des plaisirs éprouvés au cours de l'existence. Pour ne faire allusion qu'au plus vulgairement sensuel de tous, qui de nous, au réveil, n'a ressenti quelque agacement d'avoir éprouvé, en dormant, un plaisir que, si l'on ne veut pas trop se fatiguer, on ne peut plus, une fois éveillé, renouveler indéfiniment ce jour-là? C'est comme du bien perdu. On a eu du plaisir dans une autre vie qui n'est pas la nôtre. Souffrances et plaisirs du rêve (qui généralement s'évanouissent bien vite au réveil), si nous les faisons figurer dans un budget, ce n'est pas dans celui de la vie courante.

	J'ai dit deux temps; peut-être n'y en a-t-il qu'un seul, non que celui de l'homme éveillé soit valable pour le dormeur, mais peut-être parce que l'autre vie, celle où on dort, n'est pas—dans sa partie profonde—soumise à la catégorie du temps. Je me le figurais quand, aux lendemains des dîners à la Raspelière, je m'endormais si complètement. Voici pourquoi. Je commençais à me désespérer, au réveil, en voyant qu'après que j'avais sonné dix fois, le valet de chambre n'était pas venu. A la onzième il entrait. Ce n'était que la première. Les dix autres n'étaient que des ébauches, dans mon sommeil qui durait encore, du coup de sonnette que je voulais. Mes mains gourdes n'avaient seulement pas bougé. Or ces matins-là (et c'est ce qui me fait dire que le sommeil ignore peut-être la loi du temps), mon effort pour m'éveiller consistait surtout en un effort pour faire entrer le bloc obscur, non défini, du sommeil que je venais de vivre, aux cadres du temps. Ce n'est pas tâche facile; le sommeil, qui ne sait si nous avons dormi deux heures ou deux jours, ne peut nous fournir aucun point de repère. Et si nous n'en trouvons pas au dehors, ne parvenant pas à rentrer dans le temps, nous nous rendormons pour cinq minutes, qui nous semblent trois heures.

	J'ai toujours dit—et expérimenté—que le plus puissant des hypnotiques est le sommeil. Après avoir dormi profondément deux heures, s'être battu avec tant de géants, et avoir noué pour toujours tant d'amitiés, il est bien plus difficile de s'éveiller qu'après avoir pris plusieurs grammes de véronal. Aussi, raisonnant de l'un à l'autre, je fus surpris d'apprendre par le philosophe norvégien, qui le tenait de M. Boutroux, «son éminent collègue—pardon, son confrère»,—ce que M. Bergson pensait des altérations particulières de la mémoire dues aux hypnotiques. «Bien entendu, aurait dit M. Bergson à M. Boutroux, à en croire le philosophe norvégien, les hypnotiques pris de temps en temps, à doses modérées, n'ont pas d'influence sur cette solide mémoire de notre vie de tous les jours, si bien installée en nous. Mais il est d'autres mémoires, plus hautes, plus instables aussi. Un de mes collègues fait un cours d'histoire ancienne. Il m'a dit que si, la veille, il avait pris un cachet pour dormir, il avait de la peine, pendant son cours, à retrouver les citations grecques dont il avait besoin. Le docteur qui lui avait recommandé ces cachets lui assura qu'ils étaient sans influence sur la mémoire. «C'est peut-être que vous n'avez pas à faire de citations grecques», lui avait répondu l'historien, non sans un orgueil moqueur.»

	Je ne sais si cette conversation entre M. Bergson et M. Boutroux est exacte. Le philosophe norvégien, pourtant si profond et si clair, si passionnément attentif, a pu mal comprendre. Personnellement mon expérience m'a donné des résultats opposés.

	Les moments d'oubli qui suivent, le lendemain, l'ingestion de certains narcotiques ont une ressemblance partielle seulement, mais troublante, avec l'oubli qui règne au cours d'une nuit de sommeil naturel et profond. Or, ce que j'oublie dans l'un et l'autre cas, ce n'est pas tel vers de Baudelaire qui me fatigue plutôt, «ainsi qu'un tympanon», ce n'est pas tel concept d'un des philosophes cités, c'est la réalité elle-même des choses vulgaires qui m'entourent—si je dors—et dont la non-perception fait de moi un fou; c'est, si je suis éveillé et sors à la suite d'un sommeil artificiel, non pas le système de Porphyre ou de Plotin, dont je puis discuter aussi bien qu'un autre jour, mais la réponse que j'ai promis de donner à une invitation, au souvenir de laquelle s'est substitué un pur blanc. L'idée élevée est restée à sa place; ce que l'hypnotique a mis hors d'usage c'est le pouvoir d'agir dans les petites choses, dans tout ce qui demande de l'activité pour ressaisir juste à temps, pour empoigner tel souvenir de la vie de tous les jours. Malgré tout ce qu'on peut dire de la survie après la destruction du cerveau, je remarque qu'à chaque altération du cerveau correspond un fragment de mort. Nous possédons tous nos souvenirs, sinon la faculté de nous les rappeler, dit d'après M. Bergson le grand philosophe norvégien, dont je n'ai pas essayé, pour ne pas ralentir encore, d'imiter le langage. Sinon la faculté de se les rappeler. Mais qu'est-ce qu'un souvenir qu'on ne se rappelle pas? Ou bien, allons plus loin. Nous ne nous rappelons pas nos souvenirs des trente dernières années; mais ils nous baignent tout entiers; pourquoi alors s'arrêter à trente années, pourquoi ne pas prolonger jusqu'au delà de la naissance cette vie antérieure? Du moment que je ne connais pas toute une partie des souvenirs qui sont derrière moi, du moment qu'ils me sont invisibles, que je n'ai pas la faculté de les appeler à moi, qui me dit que, dans cette masse inconnue de moi, il n'y en a pas qui remontent à bien au delà de ma vie humaine? Si je puis avoir en moi et autour de moi tant de souvenirs dont je ne me souviens pas, cet oubli (du moins oubli de fait puisque je n'ai pas la faculté de rien voir) peut porter sur une vie que j'ai vécue dans le corps d'un autre homme, même sur une autre planète. Un même oubli efface tout. Mais alors que signifie cette immortalité de l'âme dont le philosophe norvégien affirmait la réalité? L'être que je serai après la mort n'a pas plus de raisons de se souvenir de l'homme que je suis depuis ma naissance que ce dernier ne se souvient de ce que j'ai été avant elle.

	Le valet de chambre entrait. Je ne lui disais pas que j'avais sonné plusieurs fois, car je me rendais compte que je n'avais fait jusque-là que le rêve que je sonnais. J'étais effrayé pourtant de penser que ce rêve avait eu la netteté de la connaissance. La connaissance aurait-elle, réciproquement, l'irréalité du rêve?

	En revanche, je lui demandais qui avait tant sonné cette nuit. Il me disait: personne, et pouvait l'affirmer, car le «tableau» des sonneries eût marqué. Pourtant j'entendais les coups répétés, presque furieux, qui vibraient encore dans mon oreille et devaient me rester perceptibles pendant plusieurs jours. Il est pourtant rare que le sommeil jette ainsi dans la vie éveillée des souvenirs qui ne meurent pas avec lui. On peut compter ces aérolithes. Si c'est une idée que le sommeil a forgée, elle se dissocie très vite en fragments ténus, irretrouvables. Mais, là, le sommeil avait fabriqué des sons. Plus matériels et plus simples, ils duraient davantage.

	J'étais étonné de l'heure relativement matinale que me disait le valet de chambre. Je n'en étais pas moins reposé. Ce sont les sommeils légers qui ont une longue durée, parce qu'intermédiaires entre la veille et le sommeil, gardant de la première une notion un peu effacée mais permanente, il leur faut infiniment plus de temps pour nous reposer qu'un sommeil profond, lequel peut être court. Je me sentais bien à mon aise pour une autre raison. S'il suffit de se rappeler qu'on s'est fatigué pour sentir péniblement sa fatigue, se dire: «Je me suis reposé» suffit à créer le repos. Or j'avais rêvé que M. de Charlus avait cent dix ans et venait de donner une paire de claques à sa propre mère; de Mme Verdurin, qu'elle avait acheté cinq milliards un bouquet de violettes; j'étais donc assuré d'avoir dormi profondément, rêvé à rebours de mes notions de la veille et de toutes les possibilités de la vie courante; cela suffisait pour que je me sentisse tout reposé.

(Please let me know, if you know what this is. Timur)

*/

